import { cp, mkdir, readdir, readFile, stat, writeFile, access } from 'node:fs/promises';
import { constants } from 'node:fs';
import { createHash } from 'node:crypto';
import { basename, dirname, join, relative, resolve } from 'node:path';
import type { ApplicationIR, PackageKind, SentenPackageManifest } from '../../core/src/index.js';
const EXCLUDES = new Set(['.git','.senten','node_modules','dist','build','coverage','.next','.turbo']);
const EXCLUDE_FILES = new Set(['senten.config.json']);
const SECRET_NAMES = [/^\.env($|\.)/i,/secret/i,/credential/i,/\.pem$/i,/\.key$/i,/id_rsa/i];
export interface PackageBuildResult { root:string; manifest:SentenPackageManifest; files:string[]; excluded:string[]; }
export async function createPackageFromDirectory(cwd:string, outRoot:string, name:string, kind:PackageKind):Promise<PackageBuildResult>{
  const packageRoot=join(outRoot,`${kind}-${safe(name)}`); await mkdir(join(packageRoot,'payload'),{recursive:true}); const files:string[]=[]; const excluded:string[]=[]; const hashes:Record<string,string>={};
  async function walk(dir:string):Promise<void>{ for(const entry of await readdir(dir)){ const src=join(dir,entry); const rel=relative(cwd,src); if(!rel)continue; const first=rel.split(/[\\/]/)[0]!; if(EXCLUDES.has(first)||EXCLUDE_FILES.has(rel.replaceAll('\\','/'))||SECRET_NAMES.some(r=>r.test(entry))){excluded.push(rel);continue;} const info=await stat(src); if(info.isDirectory())await walk(src); else if(info.isFile()){const normalized=rel.replaceAll('\\','/');const dest=join(packageRoot,'payload',rel);await mkdir(dirname(dest),{recursive:true});await cp(src,dest);files.push(normalized);hashes[normalized]=sha256(await readFile(src));} } }
  await walk(cwd); files.sort();
  const semanticPath=join(cwd,'.senten','state-truss.json'); let hasBlueprint=false; if(await exists(semanticPath)){await cp(semanticPath,join(packageRoot,'senten.blueprint.json'));hasBlueprint=true;}
  const digest=sha256(Buffer.from(files.map(f=>`${f}:${hashes[f]}`).join('\n')));
  const manifest:SentenPackageManifest={senten:1,kind,name:safe(name),version:'0.1.0',description:`${kind} created from ${basename(cwd)}`,files,integrity:{algorithm:'sha256',files:hashes,packageDigest:digest},compatibility:{senten:'>=0.8.0 <1.0.0',node:'>=22.5.0'},metadata:{semanticBlueprint:hasBlueprint}}; await writeFile(join(packageRoot,'senten.package.json'),JSON.stringify(manifest,null,2)+'\n'); return {root:packageRoot,manifest,files,excluded};
}
export async function loadPackage(path:string):Promise<SentenPackageManifest>{ return JSON.parse(await readFile(join(resolve(path),'senten.package.json'),'utf8')) as SentenPackageManifest; }
export async function verifyPackage(packageRoot:string):Promise<{ok:boolean;errors:string[];manifest:SentenPackageManifest}>{const manifest=await loadPackage(packageRoot);const errors:string[]=[];if(manifest.integrity){for(const [file,expected] of Object.entries(manifest.integrity.files)){const path=join(resolve(packageRoot),'payload',file);if(!await exists(path)){errors.push(`missing ${file}`);continue;}const actual=sha256(await readFile(path));if(actual!==expected)errors.push(`hash mismatch ${file}`);}const digest=sha256(Buffer.from((manifest.files??[]).slice().sort().map(f=>`${f}:${manifest.integrity!.files[f]}`).join('\n')));if(digest!==manifest.integrity.packageDigest)errors.push('package digest mismatch');}else errors.push('manifest has no integrity metadata');return{ok:errors.length===0,errors,manifest};}
export async function applyTemplate(packageRoot:string,target:string,variables:Record<string,string>={},options:{force?:boolean}={}):Promise<void>{ const verified=await verifyPackage(packageRoot); if(!verified.ok)throw new Error(`Package verification failed: ${verified.errors.join('; ')}`); const manifest=verified.manifest; if(manifest.kind!=='template'&&manifest.kind!=='blueprint')throw new Error(`Package ${manifest.name} is ${manifest.kind}, not a template/blueprint.`); const payload=join(resolve(packageRoot),'payload'); await copyTree(payload,target,variables,Boolean(options.force)); await mergeBlueprint(packageRoot,target); }
async function mergeBlueprint(packageRoot:string,target:string):Promise<void>{const source=join(resolve(packageRoot),'senten.blueprint.json');const dest=join(resolve(target),'.senten','state-truss.json');if(!await exists(source)||!await exists(dest))return;const incoming=JSON.parse(await readFile(source,'utf8')) as ApplicationIR;const current=JSON.parse(await readFile(dest,'utf8')) as ApplicationIR;const nodes=new Map(current.nodes.map(n=>[n.id,n]));for(const node of incoming.nodes)if(node.kind!=='application')nodes.set(node.id,node);const edgeKeys=new Set(current.edges.map(e=>`${e.from}|${e.relation}|${e.to}`));const edges=[...current.edges];for(const edge of incoming.edges){const key=`${edge.from}|${edge.relation}|${edge.to}`;if(!edgeKeys.has(key)){edges.push(edge);edgeKeys.add(key);}}await writeFile(dest,JSON.stringify({...current,nodes:[...nodes.values()],edges,generatedAt:new Date().toISOString()},null,2)+'\n');}
async function copyTree(src:string,dest:string,variables:Record<string,string>,force:boolean):Promise<void>{ await mkdir(dest,{recursive:true}); for(const entry of await readdir(src)){const from=join(src,entry);const to=join(dest,entry);const info=await stat(from);if(info.isDirectory())await copyTree(from,to,variables,force);else{if(!force&&await exists(to))throw new Error(`Template would overwrite existing file: ${to}`);await mkdir(dirname(to),{recursive:true});const content=await readFile(from);if(isProbablyText(content)){let text=content.toString('utf8');for(const [k,v] of Object.entries(variables))text=text.replaceAll(`{{${k}}}`,v);await writeFile(to,text);}else await cp(from,to);}} }
function isProbablyText(buffer:Buffer):boolean{return !buffer.subarray(0,8000).includes(0);}
function safe(input:string):string{return input.toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/(^-|-$)/g,'')||'package';}
function sha256(data:Buffer):string{return createHash('sha256').update(data).digest('hex');}
async function exists(path:string):Promise<boolean>{try{await access(path,constants.F_OK);return true;}catch{return false;}}
